require: rubocop-rails

inherit_from: .rubocop_todo.yml


AllCops:
  TargetRailsVersion: 5.2
  Exclude:
    - 'bin/*'


Layout/IndentFirstArrayElement:
  Exclude:
    - 'app/dashboards/*.rb'
    - 'db/seeds.rb'
    - 'db/seeds/*.rb'

Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'db/seeds.rb'
    - 'db/seeds/*.rb'

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 259
  Exclude:
    - 'db/seeds.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - 'db/seeds.rb'
    - 'db/seeds/*.rb'

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
